config/routes.rb
Rails.application.routes.draw do

  get 'campaigns' => 'campaigns#index'
  get 'campaigns/:id' => 'campaigns#show', as: 'campaign'

  root 'campaigns#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord

   has_many :votes

   def scores
     results = Hash.new 0
     votes.each do |vote|
       add_vote_to_results_hash(results, vote)
     end
     results
   end

   private

   def add_vote_to_results_hash(results, vote)
     if vote.validity == "during"
       results[vote.choice] += 1
     else
       results["Sent but not counted"] += 1
     end
   end

end

app/models/vote.rb
class Vote < ApplicationRecord

  validates :choice, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  def index
    @campaigns = Campaign.all
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/index.html.erb
<h1>Campaigns</h1>
<% if @campaigns.any? %>
  <% @campaigns.each do |campaign| %>
    <h3> <%= link_to campaign.name, campaign_path(campaign) %>
  <% end %>
<% else %>
  No campaigns to see
<% end %>

app/views/campaigns/show.html.erb
<h1>Campaign: <%= @campaign.name %></h1>

<h3>Scores:</h3>
<ul>
<% @campaign.scores.each do |candidate, score| %>
    <li><%= "#{candidate}: #{score}"  %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmsVotingCampaigns</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>